version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: initialize.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 600
      runas: root