spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://genshin-flow-rds.cxu6mgyqiakc.ap-northeast-2.rds.amazonaws.com:3306/genshin_flow_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
        hbm2ddl:
          auto: create

  mail:
    host: smtp.gmail.com
    username: nextconnect.lab@gmail.com
    password: ${MAIL_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  redis:
    host: localhost
    port: 6379

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

enka:
  host: https://enka.network
