spring:

  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: 'jdbc:h2:mem:test'
    username: sa
    password:
    hikari:
      connection-timeout: 1000
      validation-timeout: 1000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        hbm2ddl:
          auto: create
  h2:
    console:
      enabled: true
      path: /h2

  mail:
    host: smtp.gmail.com
    username: nextconnect.lab@gmail.com
    password: ${MAIL_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  redis:
    host: localhost
    port: 6379

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800

enka:
  host: https://enka.network